# Generated by Django 4.0.6 on 2022-07-22 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oxfordword',
            name='mp3',
        ),
        migrations.AddField(
            model_name='oxfordword',
            name='CEFR',
            field=models.CharField(choices=[('A1', 'Beginner'), ('A2', 'Elementary'), ('B1', 'Intermediate'), ('B2', 'Upper-Intermediate'), ('C1', 'Advanced'), ('C2', 'Proficiency')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oxfordword',
            name='lexical_category',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oxfordword',
            name='sound_gb',
            field=models.FileField(blank=True, upload_to='mp3s'),
        ),
        migrations.AddField(
            model_name='oxfordword',
            name='sound_us',
            field=models.FileField(blank=True, upload_to='mp3s'),
        ),
        migrations.AddField(
            model_name='oxfordword',
            name='spelling',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oxfordword',
            name='translate_ru',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='oxfordword',
            name='word',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='oxfordword',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
