# Generated by Django 4.0.6 on 2022-07-22 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_oxfordword_mp3_oxfordword_cefr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OxExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
            ],
        ),
        migrations.RenameField(
            model_name='oxfordword',
            old_name='sound_gb',
            new_name='pronunciation_gb',
        ),
        migrations.RenameField(
            model_name='oxfordword',
            old_name='sound_us',
            new_name='pronunciation_us',
        ),
        migrations.AddField(
            model_name='oxfordword',
            name='definition',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='oxfordword',
            name='topic',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='oxfordword',
            name='spelling',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='oxfordword',
            name='translate_ru',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='oxfordword',
            name='word',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='oxfordword',
            name='examples',
            field=models.ManyToManyField(blank=True, to='myapp.oxexample'),
        ),
        migrations.AddField(
            model_name='oxfordword',
            name='inflections',
            field=models.ManyToManyField(blank=True, to='myapp.inflection'),
        ),
    ]
