# Generated by Django 4.0.6 on 2022-07-22 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_inflection_oxexample_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oxfordword',
            old_name='spelling',
            new_name='spelling_gb',
        ),
        migrations.AddField(
            model_name='oxexample',
            name='translation_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='oxfordword',
            name='spelling_us',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
