# Generated by Django 4.1 on 2022-09-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_spelling_oxfordword_spelling_gb_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CEFR_Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cefr_name', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_token', models.CharField(max_length=256)),
                ('cefrs', models.ManyToManyField(blank=True, to='myapp.cefr_level')),
                ('topics', models.ManyToManyField(blank=True, to='myapp.topic')),
            ],
        ),
    ]
