# Generated by Django 4.1 on 2022-09-22 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_usersettings_learned_words_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='hard_words',
            field=models.ManyToManyField(blank=True, related_name='hardwords', to='myapp.oxfordword'),
        ),
        migrations.CreateModel(
            name='RepeatWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countdown', models.DateTimeField(auto_now=True)),
                ('oxford_word', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.oxfordword')),
            ],
        ),
        migrations.AddField(
            model_name='usersettings',
            name='repeat_words',
            field=models.ManyToManyField(blank=True, related_name='repeatwords', to='myapp.repeatword'),
        ),
    ]
