# Generated by Django 4.1 on 2022-09-22 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_repeatword_countdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repeatword',
            name='countdown',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 22, 14, 20, 45, 660616, tzinfo=datetime.timezone.utc)),
        ),
    ]
