# Generated by Django 4.1 on 2022-10-05 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rename_cefr_name_cefr_level_name_alter_topic_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('correct', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SubCourse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subcourse_title', models.CharField(max_length=100)),
                ('api_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='VideoObject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.FileField(upload_to='grinavideos')),
                ('tip', models.CharField(max_length=200)),
                ('eng_text', models.CharField(max_length=200)),
                ('ru_text', models.CharField(max_length=200)),
                ('server_choice_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sc1', to='myapp.serverchoice')),
                ('server_choice_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sc2', to='myapp.serverchoice')),
                ('server_choice_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sc3', to='myapp.serverchoice')),
                ('server_choice_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sc4', to='myapp.serverchoice')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
                ('img_uri', models.URLField()),
                ('sub_courses', models.ManyToManyField(to='myapp.subcourse')),
            ],
        ),
        migrations.CreateModel(
            name='CraftStack',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('video_objects', models.ManyToManyField(blank=True, to='myapp.videoobject')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=100)),
                ('data', models.ManyToManyField(blank=True, to='myapp.data')),
            ],
        ),
    ]
