# Generated by Django 4.1 on 2022-10-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_usersettings_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='passed_words',
            field=models.ManyToManyField(blank=True, related_name='passedwords', to='myapp.oxfordword'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='learned_courses',
            field=models.ManyToManyField(blank=True, related_name='learnedcourses', to='myapp.subcourse'),
        ),
    ]
