# Generated by Django 4.1 on 2022-10-24 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_usersettings_passed_words_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoobject',
            name='server_choice_1',
        ),
        migrations.RemoveField(
            model_name='videoobject',
            name='server_choice_2',
        ),
        migrations.RemoveField(
            model_name='videoobject',
            name='server_choice_3',
        ),
        migrations.RemoveField(
            model_name='videoobject',
            name='server_choice_4',
        ),
        migrations.AddField(
            model_name='videoobject',
            name='server_choices',
            field=models.ManyToManyField(blank=True, to='myapp.serverchoice'),
        ),
    ]
