# Generated by Django 4.1 on 2022-11-06 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='dif',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.difficulty'),
        ),
    ]
