# Generated by Django 4.1 on 2022-11-07 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_usersettings_dif'),
    ]

    operations = [
        migrations.AddField(
            model_name='difficulty',
            name='cefr',
            field=models.ManyToManyField(blank=True, to='myapp.cefr_level'),
        ),
    ]
