# Generated by Django 4.1 on 2022-11-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_difficulty_cefr'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='emoji',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='topic',
            name='title',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
