# Generated by Django 4.1 on 2022-11-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_topic_emoji_topic_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='cefrs',
        ),
        migrations.AddField(
            model_name='difficulty',
            name='desc',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='moder',
            field=models.BooleanField(default=False),
        ),
    ]
